### ISSUE TITLE
Xfce panel widgets

### ISSUE THREAD

**Issue by lisandrodemarchi** [ddnexus/Flat-Plat-Equilux#5] opened 2017-11-08 18:14 UTC
- Equilux 0.2
- GTK+ 3 version: 3.18.9
- Distribution: Xubuntu 16.04.3
- Desktop environment: Xfce 4.12

I was looking for a theme like this for a long time. It's great for graphics work. Thank a lot!

As with original Materia theme, Xfce panels have some clipped or hidden widgets:
![equilux-xfce-panel](https://user-images.githubusercontent.com/32346861/32563107-12e42f9c-c48f-11e7-8068-ee33a3bbedb7.png)

I grabbed xfce-panel related lines from arc-dark theme which has full support for xfce and added them at the end of the gtk-2.0/gtkrc file ( [gtkrc.txt](https://github.com/ddnexus/equilux-theme/files/1454835/gtkrc.txt) ). I also added some lines to the gtk-3.0/gtk.css ( [gtk.css.txt](https://github.com/ddnexus/equilux-theme/files/1454836/gtk.css.txt) ) to match the colors of gtk3 widgets to Equilux palette (for the time being, the only gtk3 widget I know in xfce-panels is the pulse-audio one).
After the patch:
![patched-xfce-panel](https://user-images.githubusercontent.com/32346861/32563116-17a695f6-c48f-11e7-8663-01ae9ec32a9e.png)

It is a dirty patch and I guess there are some unnecessary lines left but it seems to works and could be useful for other Xfce users or as the base for a proper fix by someone more skilled than me ;).

**Comment by ddnexus** [comment] 2017-11-09 03:19
Thanks for the thanks!
I think that your post should be forwarded to @nana-4 because the topic belongs to the upstream theme since it is not specific to the Equilux fork. Let's see what @nana-4 thinks about it.

**Comment by nana-4** [comment] 2017-11-09 22:39
Well, I already have a plan to support the GTK3 version of Xfce (`4.14`) with Materia:
- nana-4/materia-theme/issues/60
- https://github.com/nana-4/materia-theme/blob/master/TODO.md#supports

The reason why I focused only on the GTK3 version is that GTK2 theming is a painful task, and Xfce is just porting to GTK3. However, the full GTK3 version of Xfce may be available more later than I thought. So, I might support the current version of Xfce when I have time. 😃

**Comment by ddnexus** [comment] 2017-11-10 03:57
It looks like the cause of the problem will addressed upstream: closing the issue.

**Closed as completed by ddnexus** 2017-11-10 03:57 UTC
Labels: upstream
